package org.helios.apmrouter.catalog.domain;

// Generated Oct 27, 2012 1:30:47 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * TraceType generated by hbm2java
 */
@Document
public class TraceType implements java.io.Serializable, DomainObject {
	@SerializedName("typeId")
	@Indexed(unique=true)
	@Id
	private short typeId;
	@Expose(serialize=false)
	private String typeName;

	public TraceType() {
	}

	public TraceType(short typeId) {
		this.typeId = typeId;
	}

	public TraceType(short typeId, String typeName) {
		this.typeId = typeId;
		this.typeName = typeName;		
	}

	public short getTypeId() {
		return this.typeId;
	}

	public void setTypeId(short typeId) {
		this.typeId = typeId;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
	 * {@inheritDoc}
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TraceType [typeId=");
		builder.append(typeId);
		builder.append(", typeName=");
		builder.append(typeName);
		builder.append("]");
		return builder.toString();
	}


}
