package org.helios.apmrouter.catalog.domain;

// Generated Oct 25, 2012 9:05:53 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agent generated by hbm2java
 */
public class Agent implements java.io.Serializable {

	private Integer agentId;
	private Host host;
	private String name;
	private Date firstConnected;
	private Date lastConnected;
	private Date connected;
	private String uri;
	private Set metrics = new HashSet(0);

	public Agent() {
	}

	public Agent(Host host, String name, Date firstConnected, Date lastConnected) {
		this.host = host;
		this.name = name;
		this.firstConnected = firstConnected;
		this.lastConnected = lastConnected;
	}

	public Agent(Host host, String name, Date firstConnected,
			Date lastConnected, Date connected, String uri, Set metrics) {
		this.host = host;
		this.name = name;
		this.firstConnected = firstConnected;
		this.lastConnected = lastConnected;
		this.connected = connected;
		this.uri = uri;
		this.metrics = metrics;
	}

	public Integer getAgentId() {
		return this.agentId;
	}

	public void setAgentId(Integer agentId) {
		this.agentId = agentId;
	}

	public Host getHost() {
		return this.host;
	}

	public void setHost(Host host) {
		this.host = host;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getFirstConnected() {
		return this.firstConnected;
	}

	public void setFirstConnected(Date firstConnected) {
		this.firstConnected = firstConnected;
	}

	public Date getLastConnected() {
		return this.lastConnected;
	}

	public void setLastConnected(Date lastConnected) {
		this.lastConnected = lastConnected;
	}

	public Date getConnected() {
		return this.connected;
	}

	public void setConnected(Date connected) {
		this.connected = connected;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public Set getMetrics() {
		return this.metrics;
	}

	public void setMetrics(Set metrics) {
		this.metrics = metrics;
	}

}
