package org.helios.apmrouter.catalog.domain;

// Generated Oct 27, 2012 1:30:47 PM by Hibernate Tools 3.6.0

import java.util.Date;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 * Host generated by hbm2java
 */
public class Host implements java.io.Serializable, DomainObject {
	@SerializedName("hostId")
	private Integer hostId;
	@SerializedName("name")
	private String name;
	@SerializedName("ip")
	private String ip;
	@Expose(serialize=false)
	private String fqn;
	@Expose(serialize=false)
	private Date firstConnected;
	@Expose(serialize=false)
	private Date lastConnected;
	@SerializedName("conn")
	private Date connected;
	

	public Host() {
	}

	public Host(String name, Date firstConnected, Date lastConnected) {
		this.name = name;
		this.firstConnected = firstConnected;
		this.lastConnected = lastConnected;
	}

	public Host(String name, String ip, String fqn, Date firstConnected,
			Date lastConnected, Date connected) {
		this.name = name;
		this.ip = ip;
		this.fqn = fqn;
		this.firstConnected = firstConnected;
		this.lastConnected = lastConnected;
		this.connected = connected;		
	}

	public Integer getHostId() {
		return this.hostId;
	}

	public void setHostId(Integer hostId) {
		this.hostId = hostId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getFqn() {
		return this.fqn;
	}

	public void setFqn(String fqn) {
		this.fqn = fqn;
	}

	public Date getFirstConnected() {
		return this.firstConnected;
	}

	public void setFirstConnected(Date firstConnected) {
		this.firstConnected = firstConnected;
	}

	public Date getLastConnected() {
		return this.lastConnected;
	}

	public void setLastConnected(Date lastConnected) {
		this.lastConnected = lastConnected;
	}

	public Date getConnected() {
		return this.connected;
	}

	public void setConnected(Date connected) {
		this.connected = connected;
	}

	/**
	 * {@inheritDoc}
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Host [hostId=");
		builder.append(hostId);
		builder.append(", name=");
		builder.append(name);
		builder.append(", ip=");
		builder.append(ip);
		builder.append(", fqn=");
		builder.append(fqn);
		builder.append(", connected=");
		builder.append(connected);
		builder.append("]");
		return builder.toString();
	}


}
