package org.helios.apmrouter.catalog.domain;

// Generated Oct 25, 2012 9:05:53 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Metric generated by hbm2java
 */
public class Metric implements java.io.Serializable {

	private Long metricId;
	private TraceType traceType;
	private Agent agent;
	private String namespace;
	private short level;
	private String name;
	private Date firstSeen;
	private Date lastSeen;

	public Metric() {
	}

	public Metric(TraceType traceType, Agent agent, short level, Date firstSeen) {
		this.traceType = traceType;
		this.agent = agent;
		this.level = level;
		this.firstSeen = firstSeen;
	}

	public Metric(TraceType traceType, Agent agent, String namespace,
			short level, String name, Date firstSeen, Date lastSeen) {
		this.traceType = traceType;
		this.agent = agent;
		this.namespace = namespace;
		this.level = level;
		this.name = name;
		this.firstSeen = firstSeen;
		this.lastSeen = lastSeen;
	}

	public Long getMetricId() {
		return this.metricId;
	}

	public void setMetricId(Long metricId) {
		this.metricId = metricId;
	}

	public TraceType getTraceType() {
		return this.traceType;
	}

	public void setTraceType(TraceType traceType) {
		this.traceType = traceType;
	}

	public Agent getAgent() {
		return this.agent;
	}

	public void setAgent(Agent agent) {
		this.agent = agent;
	}

	public String getNamespace() {
		return this.namespace;
	}

	public void setNamespace(String namespace) {
		this.namespace = namespace;
	}

	public short getLevel() {
		return this.level;
	}

	public void setLevel(short level) {
		this.level = level;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getFirstSeen() {
		return this.firstSeen;
	}

	public void setFirstSeen(Date firstSeen) {
		this.firstSeen = firstSeen;
	}

	public Date getLastSeen() {
		return this.lastSeen;
	}

	public void setLastSeen(Date lastSeen) {
		this.lastSeen = lastSeen;
	}

}
